name: Build & push elasticbank container to registry

on:
  push:
    branches:
      - main  # Trigger only on main branch
    paths:
      - Dockerfile  # Trigger only on changes to the Dockerfile
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build Docker Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for pushing to ghcr.io

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Lowercase Owner Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          IMAGE_PATH=ghcr.io/${OWNER_LC}/elasticbank
          docker build -t $IMAGE_PATH:latest -f Dockerfile .
          echo "Built image: $IMAGE_PATH:latest"

      - name: Push Docker Image
        run: |
          IMAGE_PATH=ghcr.io/${OWNER_LC}/elasticbank
          docker push $IMAGE_PATH:latest
          echo "Pushed image: $IMAGE_PATH:latest"